// Code generated by protoc-gen-go. DO NOT EDIT.
// source: breez.proto

/*
Package breez is a generated protocol buffer package.

It is generated from these files:
	breez.proto

It has these top-level messages:
	OpenChannelRequest
	OpenChannelReply
	AddFundInitRequest
	AddFundInitReply
	AddFundStatusRequest
	AddFundStatusReply
	RemoveFundRequest
	RemoveFundReply
	RedeemRemovedFundsRequest
	RedeemRemovedFundsReply
	FundRequest
	FundReply
	GetSwapPaymentRequest
	GetSwapPaymentReply
	RegisterRequest
	RegisterReply
	PaymentRequest
	InvoiceReply
	UploadFileRequest
	UploadFileReply
	PingRequest
	PingReply
	OrderRequest
	OrderReply
*/
package breez

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FundReply_ReturnCode int32

const (
	FundReply_SUCCESS               FundReply_ReturnCode = 0
	FundReply_UNKNOWN_ERROR         FundReply_ReturnCode = -1
	FundReply_NODE_BUSY             FundReply_ReturnCode = -2
	FundReply_CLIENT_NOT_REGISTERED FundReply_ReturnCode = -3
	FundReply_WRONG_NODE_ID         FundReply_ReturnCode = -4
	FundReply_WRONG_AMOUNT          FundReply_ReturnCode = -5
)

var FundReply_ReturnCode_name = map[int32]string{
	0:  "SUCCESS",
	-1: "UNKNOWN_ERROR",
	-2: "NODE_BUSY",
	-3: "CLIENT_NOT_REGISTERED",
	-4: "WRONG_NODE_ID",
	-5: "WRONG_AMOUNT",
}
var FundReply_ReturnCode_value = map[string]int32{
	"SUCCESS":               0,
	"UNKNOWN_ERROR":         -1,
	"NODE_BUSY":             -2,
	"CLIENT_NOT_REGISTERED": -3,
	"WRONG_NODE_ID":         -4,
	"WRONG_AMOUNT":          -5,
}

func (x FundReply_ReturnCode) String() string {
	return proto.EnumName(FundReply_ReturnCode_name, int32(x))
}
func (FundReply_ReturnCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{11, 0} }

type OpenChannelRequest struct {
	PubKey string `protobuf:"bytes,1,opt,name=pubKey" json:"pubKey,omitempty"`
}

func (m *OpenChannelRequest) Reset()                    { *m = OpenChannelRequest{} }
func (m *OpenChannelRequest) String() string            { return proto.CompactTextString(m) }
func (*OpenChannelRequest) ProtoMessage()               {}
func (*OpenChannelRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *OpenChannelRequest) GetPubKey() string {
	if m != nil {
		return m.PubKey
	}
	return ""
}

type OpenChannelReply struct {
}

func (m *OpenChannelReply) Reset()                    { *m = OpenChannelReply{} }
func (m *OpenChannelReply) String() string            { return proto.CompactTextString(m) }
func (*OpenChannelReply) ProtoMessage()               {}
func (*OpenChannelReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type AddFundInitRequest struct {
	NodeID            string `protobuf:"bytes,1,opt,name=nodeID" json:"nodeID,omitempty"`
	NotificationToken string `protobuf:"bytes,2,opt,name=notificationToken" json:"notificationToken,omitempty"`
	Pubkey            []byte `protobuf:"bytes,3,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	Hash              []byte `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (m *AddFundInitRequest) Reset()                    { *m = AddFundInitRequest{} }
func (m *AddFundInitRequest) String() string            { return proto.CompactTextString(m) }
func (*AddFundInitRequest) ProtoMessage()               {}
func (*AddFundInitRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AddFundInitRequest) GetNodeID() string {
	if m != nil {
		return m.NodeID
	}
	return ""
}

func (m *AddFundInitRequest) GetNotificationToken() string {
	if m != nil {
		return m.NotificationToken
	}
	return ""
}

func (m *AddFundInitRequest) GetPubkey() []byte {
	if m != nil {
		return m.Pubkey
	}
	return nil
}

func (m *AddFundInitRequest) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type AddFundInitReply struct {
	Address           string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	Pubkey            []byte `protobuf:"bytes,2,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	LockHeight        int64  `protobuf:"varint,3,opt,name=lockHeight" json:"lockHeight,omitempty"`
	MaxAllowedDeposit int64  `protobuf:"varint,4,opt,name=maxAllowedDeposit" json:"maxAllowedDeposit,omitempty"`
	ErrorMessage      string `protobuf:"bytes,5,opt,name=errorMessage" json:"errorMessage,omitempty"`
}

func (m *AddFundInitReply) Reset()                    { *m = AddFundInitReply{} }
func (m *AddFundInitReply) String() string            { return proto.CompactTextString(m) }
func (*AddFundInitReply) ProtoMessage()               {}
func (*AddFundInitReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AddFundInitReply) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *AddFundInitReply) GetPubkey() []byte {
	if m != nil {
		return m.Pubkey
	}
	return nil
}

func (m *AddFundInitReply) GetLockHeight() int64 {
	if m != nil {
		return m.LockHeight
	}
	return 0
}

func (m *AddFundInitReply) GetMaxAllowedDeposit() int64 {
	if m != nil {
		return m.MaxAllowedDeposit
	}
	return 0
}

func (m *AddFundInitReply) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type AddFundStatusRequest struct {
	Addresses         []string `protobuf:"bytes,1,rep,name=addresses" json:"addresses,omitempty"`
	NotificationToken string   `protobuf:"bytes,2,opt,name=notificationToken" json:"notificationToken,omitempty"`
}

func (m *AddFundStatusRequest) Reset()                    { *m = AddFundStatusRequest{} }
func (m *AddFundStatusRequest) String() string            { return proto.CompactTextString(m) }
func (*AddFundStatusRequest) ProtoMessage()               {}
func (*AddFundStatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *AddFundStatusRequest) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func (m *AddFundStatusRequest) GetNotificationToken() string {
	if m != nil {
		return m.NotificationToken
	}
	return ""
}

type AddFundStatusReply struct {
	Statuses map[string]*AddFundStatusReply_AddressStatus `protobuf:"bytes,1,rep,name=statuses" json:"statuses,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *AddFundStatusReply) Reset()                    { *m = AddFundStatusReply{} }
func (m *AddFundStatusReply) String() string            { return proto.CompactTextString(m) }
func (*AddFundStatusReply) ProtoMessage()               {}
func (*AddFundStatusReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *AddFundStatusReply) GetStatuses() map[string]*AddFundStatusReply_AddressStatus {
	if m != nil {
		return m.Statuses
	}
	return nil
}

type AddFundStatusReply_AddressStatus struct {
	Tx        string `protobuf:"bytes,1,opt,name=tx" json:"tx,omitempty"`
	Amount    int64  `protobuf:"varint,2,opt,name=amount" json:"amount,omitempty"`
	Confirmed bool   `protobuf:"varint,3,opt,name=confirmed" json:"confirmed,omitempty"`
	BlockHash string `protobuf:"bytes,4,opt,name=blockHash" json:"blockHash,omitempty"`
}

func (m *AddFundStatusReply_AddressStatus) Reset()         { *m = AddFundStatusReply_AddressStatus{} }
func (m *AddFundStatusReply_AddressStatus) String() string { return proto.CompactTextString(m) }
func (*AddFundStatusReply_AddressStatus) ProtoMessage()    {}
func (*AddFundStatusReply_AddressStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{5, 0}
}

func (m *AddFundStatusReply_AddressStatus) GetTx() string {
	if m != nil {
		return m.Tx
	}
	return ""
}

func (m *AddFundStatusReply_AddressStatus) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *AddFundStatusReply_AddressStatus) GetConfirmed() bool {
	if m != nil {
		return m.Confirmed
	}
	return false
}

func (m *AddFundStatusReply_AddressStatus) GetBlockHash() string {
	if m != nil {
		return m.BlockHash
	}
	return ""
}

type RemoveFundRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	Amount  int64  `protobuf:"varint,2,opt,name=amount" json:"amount,omitempty"`
}

func (m *RemoveFundRequest) Reset()                    { *m = RemoveFundRequest{} }
func (m *RemoveFundRequest) String() string            { return proto.CompactTextString(m) }
func (*RemoveFundRequest) ProtoMessage()               {}
func (*RemoveFundRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *RemoveFundRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *RemoveFundRequest) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type RemoveFundReply struct {
	PaymentRequest string `protobuf:"bytes,1,opt,name=paymentRequest" json:"paymentRequest,omitempty"`
	ErrorMessage   string `protobuf:"bytes,2,opt,name=errorMessage" json:"errorMessage,omitempty"`
}

func (m *RemoveFundReply) Reset()                    { *m = RemoveFundReply{} }
func (m *RemoveFundReply) String() string            { return proto.CompactTextString(m) }
func (*RemoveFundReply) ProtoMessage()               {}
func (*RemoveFundReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *RemoveFundReply) GetPaymentRequest() string {
	if m != nil {
		return m.PaymentRequest
	}
	return ""
}

func (m *RemoveFundReply) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type RedeemRemovedFundsRequest struct {
	Paymenthash string `protobuf:"bytes,1,opt,name=paymenthash" json:"paymenthash,omitempty"`
}

func (m *RedeemRemovedFundsRequest) Reset()                    { *m = RedeemRemovedFundsRequest{} }
func (m *RedeemRemovedFundsRequest) String() string            { return proto.CompactTextString(m) }
func (*RedeemRemovedFundsRequest) ProtoMessage()               {}
func (*RedeemRemovedFundsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *RedeemRemovedFundsRequest) GetPaymenthash() string {
	if m != nil {
		return m.Paymenthash
	}
	return ""
}

type RedeemRemovedFundsReply struct {
	Txid string `protobuf:"bytes,1,opt,name=txid" json:"txid,omitempty"`
}

func (m *RedeemRemovedFundsReply) Reset()                    { *m = RedeemRemovedFundsReply{} }
func (m *RedeemRemovedFundsReply) String() string            { return proto.CompactTextString(m) }
func (*RedeemRemovedFundsReply) ProtoMessage()               {}
func (*RedeemRemovedFundsReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *RedeemRemovedFundsReply) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

type FundRequest struct {
	DeviceID    string `protobuf:"bytes,1,opt,name=deviceID" json:"deviceID,omitempty"`
	LightningID string `protobuf:"bytes,2,opt,name=lightningID" json:"lightningID,omitempty"`
	Amount      int64  `protobuf:"varint,3,opt,name=amount" json:"amount,omitempty"`
}

func (m *FundRequest) Reset()                    { *m = FundRequest{} }
func (m *FundRequest) String() string            { return proto.CompactTextString(m) }
func (*FundRequest) ProtoMessage()               {}
func (*FundRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *FundRequest) GetDeviceID() string {
	if m != nil {
		return m.DeviceID
	}
	return ""
}

func (m *FundRequest) GetLightningID() string {
	if m != nil {
		return m.LightningID
	}
	return ""
}

func (m *FundRequest) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type FundReply struct {
	ReturnCode FundReply_ReturnCode `protobuf:"varint,1,opt,name=returnCode,enum=breez.FundReply_ReturnCode" json:"returnCode,omitempty"`
}

func (m *FundReply) Reset()                    { *m = FundReply{} }
func (m *FundReply) String() string            { return proto.CompactTextString(m) }
func (*FundReply) ProtoMessage()               {}
func (*FundReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *FundReply) GetReturnCode() FundReply_ReturnCode {
	if m != nil {
		return m.ReturnCode
	}
	return FundReply_SUCCESS
}

type GetSwapPaymentRequest struct {
	PaymentRequest string `protobuf:"bytes,1,opt,name=paymentRequest" json:"paymentRequest,omitempty"`
}

func (m *GetSwapPaymentRequest) Reset()                    { *m = GetSwapPaymentRequest{} }
func (m *GetSwapPaymentRequest) String() string            { return proto.CompactTextString(m) }
func (*GetSwapPaymentRequest) ProtoMessage()               {}
func (*GetSwapPaymentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *GetSwapPaymentRequest) GetPaymentRequest() string {
	if m != nil {
		return m.PaymentRequest
	}
	return ""
}

type GetSwapPaymentReply struct {
	PaymentError string `protobuf:"bytes,1,opt,name=paymentError" json:"paymentError,omitempty"`
}

func (m *GetSwapPaymentReply) Reset()                    { *m = GetSwapPaymentReply{} }
func (m *GetSwapPaymentReply) String() string            { return proto.CompactTextString(m) }
func (*GetSwapPaymentReply) ProtoMessage()               {}
func (*GetSwapPaymentReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *GetSwapPaymentReply) GetPaymentError() string {
	if m != nil {
		return m.PaymentError
	}
	return ""
}

// The request message containing the device id and lightning id
type RegisterRequest struct {
	DeviceID    string `protobuf:"bytes,1,opt,name=deviceID" json:"deviceID,omitempty"`
	LightningID string `protobuf:"bytes,2,opt,name=lightningID" json:"lightningID,omitempty"`
}

func (m *RegisterRequest) Reset()                    { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string            { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()               {}
func (*RegisterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *RegisterRequest) GetDeviceID() string {
	if m != nil {
		return m.DeviceID
	}
	return ""
}

func (m *RegisterRequest) GetLightningID() string {
	if m != nil {
		return m.LightningID
	}
	return ""
}

// The response message containing the breez id
type RegisterReply struct {
	BreezID string `protobuf:"bytes,1,opt,name=breezID" json:"breezID,omitempty"`
}

func (m *RegisterReply) Reset()                    { *m = RegisterReply{} }
func (m *RegisterReply) String() string            { return proto.CompactTextString(m) }
func (*RegisterReply) ProtoMessage()               {}
func (*RegisterReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *RegisterReply) GetBreezID() string {
	if m != nil {
		return m.BreezID
	}
	return ""
}

type PaymentRequest struct {
	BreezID string `protobuf:"bytes,1,opt,name=breezID" json:"breezID,omitempty"`
	Invoice string `protobuf:"bytes,2,opt,name=invoice" json:"invoice,omitempty"`
	Payee   string `protobuf:"bytes,3,opt,name=payee" json:"payee,omitempty"`
	Amount  int64  `protobuf:"varint,4,opt,name=amount" json:"amount,omitempty"`
}

func (m *PaymentRequest) Reset()                    { *m = PaymentRequest{} }
func (m *PaymentRequest) String() string            { return proto.CompactTextString(m) }
func (*PaymentRequest) ProtoMessage()               {}
func (*PaymentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *PaymentRequest) GetBreezID() string {
	if m != nil {
		return m.BreezID
	}
	return ""
}

func (m *PaymentRequest) GetInvoice() string {
	if m != nil {
		return m.Invoice
	}
	return ""
}

func (m *PaymentRequest) GetPayee() string {
	if m != nil {
		return m.Payee
	}
	return ""
}

func (m *PaymentRequest) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type InvoiceReply struct {
	Error string `protobuf:"bytes,1,opt,name=Error" json:"Error,omitempty"`
}

func (m *InvoiceReply) Reset()                    { *m = InvoiceReply{} }
func (m *InvoiceReply) String() string            { return proto.CompactTextString(m) }
func (*InvoiceReply) ProtoMessage()               {}
func (*InvoiceReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *InvoiceReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type UploadFileRequest struct {
	Content []byte `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (m *UploadFileRequest) Reset()                    { *m = UploadFileRequest{} }
func (m *UploadFileRequest) String() string            { return proto.CompactTextString(m) }
func (*UploadFileRequest) ProtoMessage()               {}
func (*UploadFileRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *UploadFileRequest) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type UploadFileReply struct {
	Url string `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
}

func (m *UploadFileReply) Reset()                    { *m = UploadFileReply{} }
func (m *UploadFileReply) String() string            { return proto.CompactTextString(m) }
func (*UploadFileReply) ProtoMessage()               {}
func (*UploadFileReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *UploadFileReply) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type PingRequest struct {
}

func (m *PingRequest) Reset()                    { *m = PingRequest{} }
func (m *PingRequest) String() string            { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()               {}
func (*PingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

type PingReply struct {
	Version string `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
}

func (m *PingReply) Reset()                    { *m = PingReply{} }
func (m *PingReply) String() string            { return proto.CompactTextString(m) }
func (*PingReply) ProtoMessage()               {}
func (*PingReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *PingReply) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type OrderRequest struct {
	FullName string `protobuf:"bytes,1,opt,name=FullName" json:"FullName,omitempty"`
	Address  string `protobuf:"bytes,2,opt,name=Address" json:"Address,omitempty"`
	City     string `protobuf:"bytes,3,opt,name=City" json:"City,omitempty"`
	State    string `protobuf:"bytes,4,opt,name=State" json:"State,omitempty"`
	Zip      string `protobuf:"bytes,5,opt,name=Zip" json:"Zip,omitempty"`
	Country  string `protobuf:"bytes,6,opt,name=Country" json:"Country,omitempty"`
	Email    string `protobuf:"bytes,7,opt,name=Email" json:"Email,omitempty"`
}

func (m *OrderRequest) Reset()                    { *m = OrderRequest{} }
func (m *OrderRequest) String() string            { return proto.CompactTextString(m) }
func (*OrderRequest) ProtoMessage()               {}
func (*OrderRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *OrderRequest) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *OrderRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *OrderRequest) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *OrderRequest) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *OrderRequest) GetZip() string {
	if m != nil {
		return m.Zip
	}
	return ""
}

func (m *OrderRequest) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *OrderRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type OrderReply struct {
}

func (m *OrderReply) Reset()                    { *m = OrderReply{} }
func (m *OrderReply) String() string            { return proto.CompactTextString(m) }
func (*OrderReply) ProtoMessage()               {}
func (*OrderReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func init() {
	proto.RegisterType((*OpenChannelRequest)(nil), "breez.OpenChannelRequest")
	proto.RegisterType((*OpenChannelReply)(nil), "breez.OpenChannelReply")
	proto.RegisterType((*AddFundInitRequest)(nil), "breez.AddFundInitRequest")
	proto.RegisterType((*AddFundInitReply)(nil), "breez.AddFundInitReply")
	proto.RegisterType((*AddFundStatusRequest)(nil), "breez.AddFundStatusRequest")
	proto.RegisterType((*AddFundStatusReply)(nil), "breez.AddFundStatusReply")
	proto.RegisterType((*AddFundStatusReply_AddressStatus)(nil), "breez.AddFundStatusReply.AddressStatus")
	proto.RegisterType((*RemoveFundRequest)(nil), "breez.RemoveFundRequest")
	proto.RegisterType((*RemoveFundReply)(nil), "breez.RemoveFundReply")
	proto.RegisterType((*RedeemRemovedFundsRequest)(nil), "breez.RedeemRemovedFundsRequest")
	proto.RegisterType((*RedeemRemovedFundsReply)(nil), "breez.RedeemRemovedFundsReply")
	proto.RegisterType((*FundRequest)(nil), "breez.FundRequest")
	proto.RegisterType((*FundReply)(nil), "breez.FundReply")
	proto.RegisterType((*GetSwapPaymentRequest)(nil), "breez.GetSwapPaymentRequest")
	proto.RegisterType((*GetSwapPaymentReply)(nil), "breez.GetSwapPaymentReply")
	proto.RegisterType((*RegisterRequest)(nil), "breez.RegisterRequest")
	proto.RegisterType((*RegisterReply)(nil), "breez.RegisterReply")
	proto.RegisterType((*PaymentRequest)(nil), "breez.PaymentRequest")
	proto.RegisterType((*InvoiceReply)(nil), "breez.InvoiceReply")
	proto.RegisterType((*UploadFileRequest)(nil), "breez.UploadFileRequest")
	proto.RegisterType((*UploadFileReply)(nil), "breez.UploadFileReply")
	proto.RegisterType((*PingRequest)(nil), "breez.PingRequest")
	proto.RegisterType((*PingReply)(nil), "breez.PingReply")
	proto.RegisterType((*OrderRequest)(nil), "breez.OrderRequest")
	proto.RegisterType((*OrderReply)(nil), "breez.OrderReply")
	proto.RegisterEnum("breez.FundReply_ReturnCode", FundReply_ReturnCode_name, FundReply_ReturnCode_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Invoicer service

type InvoicerClient interface {
	RegisterDevice(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterReply, error)
	SendInvoice(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*InvoiceReply, error)
}

type invoicerClient struct {
	cc *grpc.ClientConn
}

func NewInvoicerClient(cc *grpc.ClientConn) InvoicerClient {
	return &invoicerClient{cc}
}

func (c *invoicerClient) RegisterDevice(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterReply, error) {
	out := new(RegisterReply)
	err := grpc.Invoke(ctx, "/breez.Invoicer/RegisterDevice", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *invoicerClient) SendInvoice(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*InvoiceReply, error) {
	out := new(InvoiceReply)
	err := grpc.Invoke(ctx, "/breez.Invoicer/SendInvoice", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Invoicer service

type InvoicerServer interface {
	RegisterDevice(context.Context, *RegisterRequest) (*RegisterReply, error)
	SendInvoice(context.Context, *PaymentRequest) (*InvoiceReply, error)
}

func RegisterInvoicerServer(s *grpc.Server, srv InvoicerServer) {
	s.RegisterService(&_Invoicer_serviceDesc, srv)
}

func _Invoicer_RegisterDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvoicerServer).RegisterDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/breez.Invoicer/RegisterDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvoicerServer).RegisterDevice(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Invoicer_SendInvoice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvoicerServer).SendInvoice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/breez.Invoicer/SendInvoice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvoicerServer).SendInvoice(ctx, req.(*PaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Invoicer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "breez.Invoicer",
	HandlerType: (*InvoicerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterDevice",
			Handler:    _Invoicer_RegisterDevice_Handler,
		},
		{
			MethodName: "SendInvoice",
			Handler:    _Invoicer_SendInvoice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "breez.proto",
}

// Client API for CardOrderer service

type CardOrdererClient interface {
	Order(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*OrderReply, error)
}

type cardOrdererClient struct {
	cc *grpc.ClientConn
}

func NewCardOrdererClient(cc *grpc.ClientConn) CardOrdererClient {
	return &cardOrdererClient{cc}
}

func (c *cardOrdererClient) Order(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*OrderReply, error) {
	out := new(OrderReply)
	err := grpc.Invoke(ctx, "/breez.CardOrderer/Order", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CardOrderer service

type CardOrdererServer interface {
	Order(context.Context, *OrderRequest) (*OrderReply, error)
}

func RegisterCardOrdererServer(s *grpc.Server, srv CardOrdererServer) {
	s.RegisterService(&_CardOrderer_serviceDesc, srv)
}

func _CardOrderer_Order_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardOrdererServer).Order(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/breez.CardOrderer/Order",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardOrdererServer).Order(ctx, req.(*OrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CardOrderer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "breez.CardOrderer",
	HandlerType: (*CardOrdererServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Order",
			Handler:    _CardOrderer_Order_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "breez.proto",
}

// Client API for Pos service

type PosClient interface {
	RegisterDevice(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterReply, error)
	FundChannel(ctx context.Context, in *FundRequest, opts ...grpc.CallOption) (*FundReply, error)
	UploadLogo(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*UploadFileReply, error)
}

type posClient struct {
	cc *grpc.ClientConn
}

func NewPosClient(cc *grpc.ClientConn) PosClient {
	return &posClient{cc}
}

func (c *posClient) RegisterDevice(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterReply, error) {
	out := new(RegisterReply)
	err := grpc.Invoke(ctx, "/breez.Pos/RegisterDevice", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *posClient) FundChannel(ctx context.Context, in *FundRequest, opts ...grpc.CallOption) (*FundReply, error) {
	out := new(FundReply)
	err := grpc.Invoke(ctx, "/breez.Pos/FundChannel", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *posClient) UploadLogo(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*UploadFileReply, error) {
	out := new(UploadFileReply)
	err := grpc.Invoke(ctx, "/breez.Pos/UploadLogo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Pos service

type PosServer interface {
	RegisterDevice(context.Context, *RegisterRequest) (*RegisterReply, error)
	FundChannel(context.Context, *FundRequest) (*FundReply, error)
	UploadLogo(context.Context, *UploadFileRequest) (*UploadFileReply, error)
}

func RegisterPosServer(s *grpc.Server, srv PosServer) {
	s.RegisterService(&_Pos_serviceDesc, srv)
}

func _Pos_RegisterDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PosServer).RegisterDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/breez.Pos/RegisterDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PosServer).RegisterDevice(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pos_FundChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PosServer).FundChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/breez.Pos/FundChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PosServer).FundChannel(ctx, req.(*FundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pos_UploadLogo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PosServer).UploadLogo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/breez.Pos/UploadLogo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PosServer).UploadLogo(ctx, req.(*UploadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Pos_serviceDesc = grpc.ServiceDesc{
	ServiceName: "breez.Pos",
	HandlerType: (*PosServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterDevice",
			Handler:    _Pos_RegisterDevice_Handler,
		},
		{
			MethodName: "FundChannel",
			Handler:    _Pos_FundChannel_Handler,
		},
		{
			MethodName: "UploadLogo",
			Handler:    _Pos_UploadLogo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "breez.proto",
}

// Client API for Information service

type InformationClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error)
}

type informationClient struct {
	cc *grpc.ClientConn
}

func NewInformationClient(cc *grpc.ClientConn) InformationClient {
	return &informationClient{cc}
}

func (c *informationClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error) {
	out := new(PingReply)
	err := grpc.Invoke(ctx, "/breez.Information/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Information service

type InformationServer interface {
	Ping(context.Context, *PingRequest) (*PingReply, error)
}

func RegisterInformationServer(s *grpc.Server, srv InformationServer) {
	s.RegisterService(&_Information_serviceDesc, srv)
}

func _Information_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InformationServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/breez.Information/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InformationServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Information_serviceDesc = grpc.ServiceDesc{
	ServiceName: "breez.Information",
	HandlerType: (*InformationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Information_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "breez.proto",
}

// Client API for FundManager service

type FundManagerClient interface {
	OpenChannel(ctx context.Context, in *OpenChannelRequest, opts ...grpc.CallOption) (*OpenChannelReply, error)
	AddFundInit(ctx context.Context, in *AddFundInitRequest, opts ...grpc.CallOption) (*AddFundInitReply, error)
	AddFundStatus(ctx context.Context, in *AddFundStatusRequest, opts ...grpc.CallOption) (*AddFundStatusReply, error)
	RemoveFund(ctx context.Context, in *RemoveFundRequest, opts ...grpc.CallOption) (*RemoveFundReply, error)
	RedeemRemovedFunds(ctx context.Context, in *RedeemRemovedFundsRequest, opts ...grpc.CallOption) (*RedeemRemovedFundsReply, error)
	GetSwapPayment(ctx context.Context, in *GetSwapPaymentRequest, opts ...grpc.CallOption) (*GetSwapPaymentReply, error)
}

type fundManagerClient struct {
	cc *grpc.ClientConn
}

func NewFundManagerClient(cc *grpc.ClientConn) FundManagerClient {
	return &fundManagerClient{cc}
}

func (c *fundManagerClient) OpenChannel(ctx context.Context, in *OpenChannelRequest, opts ...grpc.CallOption) (*OpenChannelReply, error) {
	out := new(OpenChannelReply)
	err := grpc.Invoke(ctx, "/breez.FundManager/OpenChannel", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fundManagerClient) AddFundInit(ctx context.Context, in *AddFundInitRequest, opts ...grpc.CallOption) (*AddFundInitReply, error) {
	out := new(AddFundInitReply)
	err := grpc.Invoke(ctx, "/breez.FundManager/AddFundInit", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fundManagerClient) AddFundStatus(ctx context.Context, in *AddFundStatusRequest, opts ...grpc.CallOption) (*AddFundStatusReply, error) {
	out := new(AddFundStatusReply)
	err := grpc.Invoke(ctx, "/breez.FundManager/AddFundStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fundManagerClient) RemoveFund(ctx context.Context, in *RemoveFundRequest, opts ...grpc.CallOption) (*RemoveFundReply, error) {
	out := new(RemoveFundReply)
	err := grpc.Invoke(ctx, "/breez.FundManager/RemoveFund", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fundManagerClient) RedeemRemovedFunds(ctx context.Context, in *RedeemRemovedFundsRequest, opts ...grpc.CallOption) (*RedeemRemovedFundsReply, error) {
	out := new(RedeemRemovedFundsReply)
	err := grpc.Invoke(ctx, "/breez.FundManager/RedeemRemovedFunds", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fundManagerClient) GetSwapPayment(ctx context.Context, in *GetSwapPaymentRequest, opts ...grpc.CallOption) (*GetSwapPaymentReply, error) {
	out := new(GetSwapPaymentReply)
	err := grpc.Invoke(ctx, "/breez.FundManager/GetSwapPayment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FundManager service

type FundManagerServer interface {
	OpenChannel(context.Context, *OpenChannelRequest) (*OpenChannelReply, error)
	AddFundInit(context.Context, *AddFundInitRequest) (*AddFundInitReply, error)
	AddFundStatus(context.Context, *AddFundStatusRequest) (*AddFundStatusReply, error)
	RemoveFund(context.Context, *RemoveFundRequest) (*RemoveFundReply, error)
	RedeemRemovedFunds(context.Context, *RedeemRemovedFundsRequest) (*RedeemRemovedFundsReply, error)
	GetSwapPayment(context.Context, *GetSwapPaymentRequest) (*GetSwapPaymentReply, error)
}

func RegisterFundManagerServer(s *grpc.Server, srv FundManagerServer) {
	s.RegisterService(&_FundManager_serviceDesc, srv)
}

func _FundManager_OpenChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FundManagerServer).OpenChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/breez.FundManager/OpenChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FundManagerServer).OpenChannel(ctx, req.(*OpenChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FundManager_AddFundInit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFundInitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FundManagerServer).AddFundInit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/breez.FundManager/AddFundInit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FundManagerServer).AddFundInit(ctx, req.(*AddFundInitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FundManager_AddFundStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFundStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FundManagerServer).AddFundStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/breez.FundManager/AddFundStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FundManagerServer).AddFundStatus(ctx, req.(*AddFundStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FundManager_RemoveFund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveFundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FundManagerServer).RemoveFund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/breez.FundManager/RemoveFund",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FundManagerServer).RemoveFund(ctx, req.(*RemoveFundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FundManager_RedeemRemovedFunds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RedeemRemovedFundsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FundManagerServer).RedeemRemovedFunds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/breez.FundManager/RedeemRemovedFunds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FundManagerServer).RedeemRemovedFunds(ctx, req.(*RedeemRemovedFundsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FundManager_GetSwapPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSwapPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FundManagerServer).GetSwapPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/breez.FundManager/GetSwapPayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FundManagerServer).GetSwapPayment(ctx, req.(*GetSwapPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FundManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "breez.FundManager",
	HandlerType: (*FundManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OpenChannel",
			Handler:    _FundManager_OpenChannel_Handler,
		},
		{
			MethodName: "AddFundInit",
			Handler:    _FundManager_AddFundInit_Handler,
		},
		{
			MethodName: "AddFundStatus",
			Handler:    _FundManager_AddFundStatus_Handler,
		},
		{
			MethodName: "RemoveFund",
			Handler:    _FundManager_RemoveFund_Handler,
		},
		{
			MethodName: "RedeemRemovedFunds",
			Handler:    _FundManager_RedeemRemovedFunds_Handler,
		},
		{
			MethodName: "GetSwapPayment",
			Handler:    _FundManager_GetSwapPayment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "breez.proto",
}

func init() { proto.RegisterFile("breez.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1225 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0xdb, 0x6e, 0x1b, 0x45,
	0x18, 0xf6, 0xda, 0x71, 0x1b, 0xff, 0x3e, 0xd4, 0x99, 0x26, 0xa9, 0xb3, 0xad, 0xaa, 0x68, 0xa0,
	0x50, 0xa4, 0xd6, 0x12, 0x41, 0x48, 0x40, 0x55, 0x91, 0xc4, 0x76, 0x82, 0xd5, 0xc4, 0x8e, 0xd6,
	0x89, 0x0a, 0x48, 0x28, 0xda, 0x78, 0x27, 0xce, 0x2a, 0xeb, 0x99, 0x65, 0x76, 0x9d, 0xc6, 0x3c,
	0x00, 0x12, 0x6f, 0xc2, 0x25, 0x17, 0x88, 0x6b, 0x1e, 0x80, 0xb7, 0xe1, 0x92, 0xa3, 0xe6, 0xb0,
	0x27, 0xdb, 0x89, 0x40, 0xaa, 0xaf, 0xf6, 0x3f, 0xcc, 0x3f, 0xdf, 0x7c, 0xff, 0x37, 0x07, 0x43,
	0xf9, 0x8c, 0x13, 0xf2, 0x5d, 0xd3, 0xe7, 0x2c, 0x64, 0xa8, 0x28, 0x0d, 0xfc, 0x0c, 0x50, 0xdf,
	0x27, 0xb4, 0x75, 0x61, 0x53, 0x4a, 0x3c, 0x8b, 0x7c, 0x3b, 0x21, 0x41, 0x88, 0xd6, 0xe1, 0x8e,
	0x3f, 0x39, 0x7b, 0x45, 0xa6, 0x0d, 0x63, 0xd3, 0x78, 0x5a, 0xb2, 0xb4, 0x85, 0x11, 0xd4, 0x33,
	0xd9, 0xbe, 0x37, 0xc5, 0xdf, 0x1b, 0x80, 0x76, 0x1c, 0x67, 0x6f, 0x42, 0x9d, 0x2e, 0x75, 0xc3,
	0x54, 0x09, 0xca, 0x1c, 0xd2, 0x6d, 0x47, 0x25, 0x94, 0x85, 0x9e, 0xc1, 0x0a, 0x65, 0xa1, 0x7b,
	0xee, 0x0e, 0xed, 0xd0, 0x65, 0xf4, 0x98, 0x5d, 0x12, 0xda, 0xc8, 0xcb, 0x94, 0xf9, 0x80, 0x06,
	0x72, 0x49, 0xa6, 0x8d, 0xc2, 0xa6, 0xf1, 0xb4, 0x62, 0x69, 0x0b, 0x21, 0x58, 0xba, 0xb0, 0x83,
	0x8b, 0xc6, 0x92, 0xf4, 0xca, 0x6f, 0xfc, 0x8b, 0x01, 0xf5, 0x0c, 0x10, 0xdf, 0x9b, 0xa2, 0x06,
	0xdc, 0xb5, 0x1d, 0x87, 0x93, 0x20, 0xd0, 0x38, 0x22, 0x33, 0x55, 0x3a, 0x9f, 0x29, 0xfd, 0x18,
	0xc0, 0x63, 0xc3, 0xcb, 0x2f, 0x88, 0x3b, 0xba, 0x08, 0xe5, 0xb4, 0x05, 0x2b, 0xe5, 0x11, 0x0b,
	0x18, 0xdb, 0xd7, 0x3b, 0x9e, 0xc7, 0xde, 0x10, 0xa7, 0x4d, 0x7c, 0x16, 0xb8, 0xa1, 0xc4, 0x51,
	0xb0, 0xe6, 0x03, 0x08, 0x43, 0x85, 0x70, 0xce, 0xf8, 0x21, 0x09, 0x02, 0x7b, 0x44, 0x1a, 0x45,
	0x09, 0x22, 0xe3, 0xc3, 0x67, 0xb0, 0xaa, 0x71, 0x0f, 0x42, 0x3b, 0x9c, 0x04, 0x11, 0x85, 0x8f,
	0xa0, 0xa4, 0xc1, 0x12, 0x81, 0xbe, 0xf0, 0xb4, 0x64, 0x25, 0x8e, 0xff, 0x47, 0x24, 0xfe, 0x39,
	0x1f, 0x77, 0x29, 0x9a, 0x44, 0xd0, 0xd3, 0x82, 0xe5, 0x40, 0x9a, 0x7a, 0x86, 0xf2, 0xd6, 0xfb,
	0x4d, 0xa5, 0x92, 0xf9, 0xe4, 0xe6, 0x40, 0x67, 0x76, 0x68, 0xc8, 0xa7, 0x56, 0x3c, 0xd0, 0x0c,
	0xa0, 0xba, 0xa3, 0x60, 0xa9, 0x0c, 0x54, 0x83, 0x7c, 0x78, 0xad, 0xf9, 0xce, 0x87, 0xd7, 0x82,
	0x6a, 0x7b, 0xcc, 0x26, 0x34, 0x94, 0xf8, 0x0a, 0x96, 0xb6, 0xc4, 0x02, 0x87, 0x8c, 0x9e, 0xbb,
	0x7c, 0x4c, 0x1c, 0xc9, 0xf4, 0xb2, 0x95, 0x38, 0x44, 0xf4, 0x4c, 0xf2, 0x1e, 0x35, 0xba, 0x64,
	0x25, 0x0e, 0xd3, 0x81, 0x6a, 0x06, 0x0f, 0xaa, 0x43, 0xe1, 0x32, 0x16, 0xac, 0xf8, 0x44, 0x2f,
	0xa1, 0x78, 0x65, 0x7b, 0x13, 0x22, 0x67, 0xbd, 0x75, 0x65, 0x19, 0xf8, 0x96, 0x1a, 0xf5, 0x59,
	0xfe, 0x13, 0x03, 0x77, 0x60, 0xc5, 0x22, 0x63, 0x76, 0x45, 0xc4, 0x88, 0xa8, 0x2f, 0xb7, 0x6a,
	0x6a, 0xd1, 0x42, 0xf1, 0x37, 0x70, 0x2f, 0x5d, 0x46, 0x30, 0xff, 0x1e, 0xd4, 0x7c, 0x7b, 0x3a,
	0x26, 0x34, 0xda, 0x31, 0xba, 0xd6, 0x8c, 0x77, 0x4e, 0x40, 0xf9, 0x05, 0x02, 0x7a, 0x09, 0x1b,
	0x16, 0x71, 0x08, 0x19, 0xab, 0x49, 0xe4, 0xf2, 0x62, 0x15, 0x6d, 0x42, 0x59, 0x97, 0x94, 0x3b,
	0x46, 0xcd, 0x92, 0x76, 0xe1, 0xe7, 0xf0, 0x60, 0xd1, 0x70, 0x81, 0x12, 0xc1, 0x52, 0x78, 0xed,
	0x3a, 0x7a, 0x94, 0xfc, 0xc6, 0x43, 0x28, 0xa7, 0xd9, 0x30, 0x61, 0xd9, 0x21, 0x57, 0xee, 0x30,
	0xd9, 0xea, 0xb1, 0x2d, 0xe6, 0xf6, 0xc4, 0xa6, 0xa1, 0x2e, 0x1d, 0x75, 0xdb, 0x1a, 0x7b, 0xda,
	0x95, 0x62, 0xac, 0x90, 0x61, 0xec, 0x77, 0x03, 0x4a, 0x09, 0x59, 0x2f, 0x00, 0x38, 0x09, 0x27,
	0x9c, 0xb6, 0x98, 0x43, 0xe4, 0x2c, 0xb5, 0xad, 0x87, 0xba, 0x9d, 0x71, 0x56, 0xd3, 0x8a, 0x53,
	0xac, 0x54, 0x3a, 0xfe, 0xd1, 0x00, 0x48, 0x42, 0xa8, 0x0c, 0x77, 0x07, 0x27, 0xad, 0x56, 0x67,
	0x30, 0xa8, 0xe7, 0x90, 0x09, 0xd5, 0x93, 0xde, 0xab, 0x5e, 0xff, 0x75, 0xef, 0xb4, 0x63, 0x59,
	0x7d, 0xab, 0xfe, 0x4f, 0xf4, 0x33, 0xd0, 0x3a, 0x94, 0x7a, 0xfd, 0x76, 0xe7, 0x74, 0xf7, 0x64,
	0xf0, 0x55, 0xfd, 0xef, 0xc4, 0x8f, 0x61, 0xad, 0x75, 0xd0, 0xed, 0xf4, 0x8e, 0x4f, 0x7b, 0xfd,
	0xe3, 0x53, 0xab, 0xb3, 0xdf, 0x1d, 0x1c, 0x77, 0xac, 0x4e, 0xbb, 0xfe, 0x57, 0x92, 0x63, 0x42,
	0xf5, 0xb5, 0xd5, 0xef, 0xed, 0x9f, 0xca, 0x0a, 0xdd, 0x76, 0xfd, 0xcf, 0x24, 0xb6, 0x01, 0x15,
	0x15, 0xdb, 0x39, 0xec, 0x9f, 0xf4, 0x8e, 0xeb, 0x7f, 0xc4, 0x21, 0xfc, 0x39, 0xac, 0xed, 0x93,
	0x70, 0xf0, 0xc6, 0xf6, 0x8f, 0xb2, 0x2a, 0xf8, 0x8f, 0x6a, 0xc1, 0x9f, 0xc2, 0xfd, 0xd9, 0x02,
	0x82, 0x3f, 0x0c, 0x15, 0x9d, 0xd8, 0x11, 0xba, 0xd1, 0x83, 0x33, 0x3e, 0xdc, 0x17, 0x1a, 0x1d,
	0xb9, 0x41, 0x48, 0xf8, 0x5b, 0x69, 0x2d, 0xfe, 0x00, 0xaa, 0x49, 0x41, 0x7d, 0x16, 0xcb, 0x96,
	0xc5, 0xd5, 0x22, 0x13, 0x73, 0xa8, 0xcd, 0x2c, 0xf8, 0xc6, 0x5c, 0x11, 0x71, 0xe9, 0x15, 0x73,
	0x87, 0xd1, 0x5e, 0x88, 0x4c, 0xb4, 0x0a, 0x45, 0xdf, 0x9e, 0x12, 0x22, 0xa5, 0x54, 0xb2, 0x94,
	0x91, 0x52, 0xd8, 0x52, 0x46, 0x61, 0xef, 0x42, 0xa5, 0xab, 0x06, 0x2a, 0x74, 0xab, 0x50, 0x4c,
	0x93, 0xa3, 0x0c, 0xfc, 0x1c, 0x56, 0x4e, 0x7c, 0x8f, 0xd9, 0xce, 0x9e, 0xeb, 0x91, 0x14, 0xb8,
	0x21, 0xa3, 0x21, 0xa1, 0xaa, 0x0d, 0x15, 0x2b, 0x32, 0xf1, 0x3b, 0x70, 0x2f, 0x9d, 0x2e, 0xea,
	0xd6, 0xa1, 0x30, 0xe1, 0x5e, 0x74, 0x2e, 0x4d, 0xb8, 0x87, 0xab, 0x50, 0x3e, 0x72, 0xe9, 0x28,
	0xea, 0xd9, 0x13, 0x28, 0x29, 0x53, 0x73, 0x74, 0x45, 0x78, 0xe0, 0x32, 0x1a, 0xad, 0x5b, 0x9b,
	0xf8, 0x27, 0x03, 0x2a, 0x7d, 0xee, 0x64, 0xba, 0xb3, 0x37, 0xf1, 0xbc, 0x9e, 0x3d, 0x26, 0x51,
	0x77, 0x22, 0x5b, 0x94, 0xd1, 0x67, 0x5a, 0x44, 0x92, 0x36, 0xc5, 0x8e, 0x6e, 0xb9, 0xe1, 0x54,
	0x73, 0x24, 0xbf, 0xc5, 0xd2, 0xc5, 0xd1, 0x47, 0xf4, 0x29, 0xab, 0x0c, 0x01, 0xfc, 0x6b, 0xd7,
	0xd7, 0x37, 0x96, 0xf8, 0x14, 0x55, 0x5b, 0x82, 0x3b, 0x3e, 0x6d, 0xdc, 0x51, 0x55, 0xb5, 0x29,
	0xc9, 0x1b, 0xdb, 0xae, 0xd7, 0xb8, 0xab, 0xc9, 0x13, 0x06, 0xae, 0x00, 0x68, 0xc4, 0xbe, 0x37,
	0xdd, 0xfa, 0xc1, 0x80, 0x65, 0xcd, 0x38, 0x47, 0xdb, 0x50, 0x8b, 0xc4, 0xd1, 0x96, 0x92, 0x42,
	0xeb, 0x7a, 0x3f, 0xcf, 0x88, 0xd0, 0x5c, 0x9d, 0xf3, 0x8b, 0x57, 0x47, 0x0e, 0xbd, 0x80, 0xf2,
	0x80, 0x88, 0xab, 0x5e, 0x35, 0x7f, 0x4d, 0xa7, 0x65, 0x75, 0x64, 0xde, 0xd7, 0xee, 0x74, 0xab,
	0x71, 0x6e, 0x6b, 0x1b, 0xca, 0x2d, 0x9b, 0x3b, 0x12, 0x1d, 0xe1, 0xe8, 0x43, 0x28, 0xca, 0x4f,
	0x14, 0xa5, 0xa7, 0x89, 0x36, 0x57, 0xb2, 0x4e, 0x55, 0xe1, 0x57, 0x03, 0x0a, 0x47, 0x2c, 0x78,
	0x0b, 0x0b, 0xf9, 0x58, 0x9d, 0xa7, 0xfa, 0x51, 0x85, 0x50, 0xe6, 0x5c, 0x53, 0x43, 0xeb, 0xb3,
	0x67, 0x1d, 0xce, 0xa1, 0x6d, 0x00, 0x25, 0xb5, 0x03, 0x36, 0x62, 0xa8, 0xa1, 0x33, 0xe6, 0xc4,
	0x6a, 0xae, 0x2f, 0x88, 0xa8, 0x25, 0xbc, 0x84, 0x72, 0x97, 0x9e, 0x33, 0x3e, 0x96, 0xef, 0x04,
	0xd4, 0x84, 0x25, 0xa1, 0xc3, 0x18, 0x40, 0x4a, 0xa3, 0x31, 0x80, 0x58, 0xa8, 0x38, 0xb7, 0xf5,
	0x5b, 0x41, 0x01, 0x3f, 0xb4, 0xa9, 0x3d, 0x22, 0x1c, 0xb5, 0xa0, 0x9c, 0x7a, 0x1c, 0xa2, 0x8d,
	0x88, 0xb5, 0xb9, 0xe7, 0xa5, 0xf9, 0x60, 0x51, 0x48, 0xad, 0xaa, 0x05, 0xe5, 0xd4, 0x1b, 0x2e,
	0x2e, 0x32, 0xff, 0xc0, 0x8c, 0x8b, 0xcc, 0x3e, 0xf9, 0x70, 0x0e, 0x75, 0xe5, 0x83, 0x24, 0xb9,
	0xe4, 0xd1, 0xc3, 0xc5, 0x57, 0xbf, 0x2a, 0xb4, 0x71, 0xe3, 0xbb, 0x40, 0xb1, 0x9c, 0xdc, 0xdc,
	0x31, 0xcb, 0x73, 0x6f, 0x02, 0x73, 0x7d, 0x41, 0x44, 0x55, 0xf8, 0x12, 0xd0, 0xfc, 0xed, 0x8a,
	0x36, 0xe3, 0xfc, 0x1b, 0xee, 0x6d, 0xf3, 0xf1, 0x2d, 0x19, 0xaa, 0xf2, 0x01, 0xd4, 0xb2, 0x87,
	0x3d, 0x7a, 0xa4, 0xc7, 0x2c, 0xbc, 0x44, 0x4c, 0xf3, 0x86, 0xa8, 0xac, 0xb6, 0xfb, 0x04, 0xd6,
	0x5c, 0xd6, 0x1c, 0x71, 0x7f, 0xa8, 0xd3, 0x02, 0xc2, 0x85, 0x9e, 0x77, 0x61, 0x57, 0x98, 0x47,
	0xe2, 0x5f, 0xc3, 0x91, 0x71, 0x76, 0x47, 0xfe, 0x7d, 0xf8, 0xe8, 0xdf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x27, 0xb2, 0x0e, 0x65, 0x4d, 0x0c, 0x00, 0x00,
}
